# Generated by Django 2.2.19 on 2022-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
